<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "pay_multi_curency".
 *
 * @property integer $id
 * @property string $amount_kip
 * @property string $amount_th
 * @property string $amount_usd
 * @property integer $invoice_id
 *
 * @property \app\models\Invoice $invoice
 * @property string $aliasModel
 */
abstract class PayMultiCurency extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'pay_multi_curency';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['invoice_id'], 'required'],
            [['invoice_id'], 'integer'],
            [['amount_kip', 'amount_th', 'amount_usd'], 'string', 'max' => 255],
            [['invoice_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Invoice::className(), 'targetAttribute' => ['invoice_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'amount_kip' => Yii::t('models', 'Amount Kip'),
            'amount_th' => Yii::t('models', 'Amount Th'),
            'amount_usd' => Yii::t('models', 'Amount Usd'),
            'invoice_id' => Yii::t('models', 'Invoice ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoice()
    {
        return $this->hasOne(\app\models\Invoice::className(), ['id' => 'invoice_id']);
    }




}
