<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "profile_branch".
 *
 * @property integer $id
 * @property string $shop_name
 * @property string $telephone
 * @property string $phone_number
 * @property string $email
 * @property string $address
 * @property integer $branch_id
 *
 * @property \app\models\Branch $branch
 * @property string $aliasModel
 */
abstract class ProfileBranch extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'profile_branch';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['address'], 'string'],
            [['branch_id'], 'required'],
            [['branch_id'], 'integer'],
            [['shop_name'], 'string', 'max' => 255],
            [['telephone', 'phone_number', 'email'], 'string', 'max' => 45],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'shop_name' => Yii::t('models', 'Shop Name'),
            'telephone' => Yii::t('models', 'Telephone'),
            'phone_number' => Yii::t('models', 'Phone Number'),
            'email' => Yii::t('models', 'Email'),
            'address' => Yii::t('models', 'Address'),
            'branch_id' => Yii::t('models', 'Branch ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }




}
