<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "still_pay".
 *
 * @property integer $id
 * @property string $name
 * @property string $details
 * @property string $price
 * @property string $date
 * @property integer $status
 * @property integer $custommer_id
 *
 * @property \app\models\Custommer $custommer
 * @property string $aliasModel
 */
abstract class StillPay extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'still_pay';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['details', 'price', 'date', 'custommer_id'], 'required'],
            [['details'], 'string'],
            [['date'], 'safe'],
            [['custommer_id'], 'integer'],
            [['name', 'price'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 1],
            [['custommer_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Custommer::className(), 'targetAttribute' => ['custommer_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'Name',
            'details' => 'Details',
            'price' => 'Price',
            'date' => 'Date',
            'status' => 'Status',
            'custommer_id' => 'Custommer ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getCustommer()
    {
        return $this->hasOne(\app\models\Custommer::className(), ['id' => 'custommer_id']);
    }




}
