<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "user".
 *
 * @property integer $id
 * @property string $photo
 * @property string $first_name
 * @property string $last_name
 * @property string $username
 * @property string $password
 * @property integer $status
 * @property string $user_type
 * @property string $date
 * @property string $height_screen
 * @property integer $branch_id
 *
 * @property \app\models\Barcode[] $barcodes
 * @property \app\models\Invoice[] $invoices
 * @property \app\models\ProductTransfer[] $productTransfers
 * @property \app\models\ProductTransfer[] $productTransfers0
 * @property \app\models\Products[] $products
 * @property \app\models\Sale[] $sales
 * @property \app\models\Branch $branch
 * @property string $aliasModel
 */
abstract class User extends \yii\db\ActiveRecord
{



    /**
    * ENUM field values
    */
    const USER_TYPE_ADMIN = 'Admin';
    const USER_TYPE_USER = 'User';
    const USER_TYPE_POS = 'POS';
    var $enum_labels = false;
    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'user';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['first_name', 'username', 'password', 'user_type', 'date'], 'required'],
            [['status', 'branch_id'], 'integer'],
            [['user_type'], 'string'],
            [['date'], 'safe'],
            [['photo'], 'string', 'max' => 45],
            [['first_name', 'last_name', 'username', 'password'], 'string', 'max' => 255],
            [['height_screen'], 'string', 'max' => 10],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
            ['user_type', 'in', 'range' => [
                    self::USER_TYPE_ADMIN,
                    self::USER_TYPE_USER,
                    self::USER_TYPE_POS,
                ]
            ]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'photo' => Yii::t('models', 'Photo'),
            'first_name' => Yii::t('models', 'First Name'),
            'last_name' => Yii::t('models', 'Last Name'),
            'username' => Yii::t('models', 'Username'),
            'password' => Yii::t('models', 'Password'),
            'status' => Yii::t('models', 'Status'),
            'user_type' => Yii::t('models', 'User Type'),
            'date' => Yii::t('models', 'Date'),
            'height_screen' => Yii::t('models', 'Height Screen'),
            'branch_id' => Yii::t('models', 'Branch ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarcodes()
    {
        return $this->hasMany(\app\models\Barcode::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getInvoices()
    {
        return $this->hasMany(\app\models\Invoice::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductTransfers()
    {
        return $this->hasMany(\app\models\ProductTransfer::className(), ['tra_user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProductTransfers0()
    {
        return $this->hasMany(\app\models\ProductTransfer::className(), ['get_user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasMany(\app\models\Products::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSales()
    {
        return $this->hasMany(\app\models\Sale::className(), ['user_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }




    /**
     * get column user_type enum value label
     * @param string $value
     * @return string
     */
    public static function getUserTypeValueLabel($value){
        $labels = self::optsUserType();
        if(isset($labels[$value])){
            return $labels[$value];
        }
        return $value;
    }

    /**
     * column user_type ENUM value labels
     * @return array
     */
    public static function optsUserType()
    {
        return [
            self::USER_TYPE_ADMIN => Yii::t('models', 'Admin'),
            self::USER_TYPE_USER => Yii::t('models', 'User'),
            self::USER_TYPE_POS => Yii::t('models', 'Pos'),
        ];
    }

}
