<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "currency".
 *
 * @property integer $id
 * @property string $name
 * @property string $code
 * @property string $rate
 * @property double $round_exch
 * @property integer $base_currency
 *
 * @property \app\models\Purchase[] $purchases
 * @property string $aliasModel
 */
abstract class Currency extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'currency';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'round_exch'], 'required'],
            [['round_exch'], 'number'],
            [['base_currency'], 'integer'],
            [['name', 'code'], 'string', 'max' => 255],
            [['rate'], 'string', 'max' => 45]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'name' => Yii::t('models', 'Name'),
            'code' => Yii::t('models', 'Code'),
            'rate' => Yii::t('models', 'Rate'),
            'round_exch' => Yii::t('models', 'Round Exch'),
            'base_currency' => Yii::t('models', 'Base Currency'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchases()
    {
        return $this->hasMany(\app\models\Purchase::className(), ['currency_id' => 'id']);
    }




}
