<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "invoice".
 *
 * @property integer $id
 * @property string $code
 * @property string $full_name
 * @property string $phone
 * @property string $date
 * @property integer $user_id
 *
 * @property \app\models\Barcode[] $barcodes
 * @property \app\models\Discount[] $discounts
 * @property \app\models\User $user
 * @property \app\models\Sale[] $sales
 * @property string $aliasModel
 */
abstract class Invoice extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'invoice';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['code', 'date'], 'required'],
            [['date'], 'safe'],
            [['user_id'], 'integer'],
            [['code', 'phone'], 'string', 'max' => 45],
            [['full_name'], 'string', 'max' => 255],
            [['user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'code' => 'Code',
            'full_name' => 'Full Name',
            'phone' => 'Phone',
            'date' => 'Date',
            'user_id' => 'User ID',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBarcodes()
    {
        return $this->hasMany(\app\models\Barcode::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getDiscounts()
    {
        return $this->hasMany(\app\models\Discount::className(), ['invoice_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSales()
    {
        return $this->hasMany(\app\models\Sale::className(), ['invoice_id' => 'id']);
    }




}
