<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "item_transfer_to_warehouse".
 *
 * @property integer $id
 * @property integer $qautity
 * @property string $date
 * @property string $status
 * @property integer $branch_id
 * @property integer $products_id
 *
 * @property \app\models\Branch $branch
 * @property \app\models\Products $products
 * @property string $aliasModel
 */
abstract class Itemtransferwarehouse extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'item_transfer_to_warehouse';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['qautity', 'branch_id', 'products_id'], 'integer'],
            [['date', 'status', 'branch_id', 'products_id'], 'required'],
            [['date'], 'safe'],
            [['status'], 'string', 'max' => 45],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
            [['products_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Products::className(), 'targetAttribute' => ['products_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'qautity' => Yii::t('models', 'Qautity'),
            'date' => Yii::t('models', 'Date'),
            'status' => Yii::t('models', 'Status'),
            'branch_id' => Yii::t('models', 'Branch ID'),
            'products_id' => Yii::t('models', 'Products ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasOne(\app\models\Products::className(), ['id' => 'products_id']);
    }




}
