<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "product_transfer".
 *
 * @property integer $id
 * @property string $date
 * @property integer $status
 * @property integer $branch_id
 *
 * @property \app\models\ItemTransfer[] $itemTransfers
 * @property \app\models\Branch $branch
 * @property string $aliasModel
 */
abstract class ProductTransfer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_transfer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date', 'branch_id'], 'required'],
            [['date'], 'safe'],
            [['status', 'branch_id'], 'integer'],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date' => Yii::t('models', 'Date'),
            'status' => Yii::t('models', 'Status'),
            'branch_id' => Yii::t('models', 'Branch ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemTransfers()
    {
        return $this->hasMany(\app\models\ItemTransfer::className(), ['product_transfer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }




}
