<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "product_transfer".
 *
 * @property integer $id
 * @property string $date_create
 * @property string $date_edit
 * @property integer $status
 * @property integer $branch_id
 * @property integer $tra_user_id
 * @property integer $get_user_id
 *
 * @property \app\models\ItemTransfer[] $itemTransfers
 * @property \app\models\Branch $branch
 * @property \app\models\User $traUser
 * @property \app\models\User $getUser
 * @property string $aliasModel
 */
abstract class ProductTransfer extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'product_transfer';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['date_create', 'date_edit', 'branch_id'], 'required'],
            [['date_create', 'date_edit'], 'safe'],
            [['status', 'branch_id', 'tra_user_id', 'get_user_id'], 'integer'],
            [['branch_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Branch::className(), 'targetAttribute' => ['branch_id' => 'id']],
            [['tra_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['tra_user_id' => 'id']],
            [['get_user_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\User::className(), 'targetAttribute' => ['get_user_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date_create' => Yii::t('models', 'Date Create'),
            'date_edit' => Yii::t('models', 'Date Edit'),
            'status' => Yii::t('models', 'Status'),
            'branch_id' => Yii::t('models', 'Branch ID'),
            'tra_user_id' => Yii::t('models', 'Tra User ID'),
            'get_user_id' => Yii::t('models', 'Get User ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getItemTransfers()
    {
        return $this->hasMany(\app\models\ItemTransfer::className(), ['product_transfer_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getBranch()
    {
        return $this->hasOne(\app\models\Branch::className(), ['id' => 'branch_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTraUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'tra_user_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getGetUser()
    {
        return $this->hasOne(\app\models\User::className(), ['id' => 'get_user_id']);
    }




}
