<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "purchase_item".
 *
 * @property integer $id
 * @property string $date
 * @property string $pricebuy
 * @property integer $qautity
 * @property string $date_exp
 * @property integer $products_id
 * @property integer $purchase_id
 *
 * @property \app\models\Purchase $purchase
 * @property \app\models\Products $products
 * @property \app\models\SaleHasPurchase[] $saleHasPurchases
 * @property \app\models\Sale[] $sales
 * @property string $aliasModel
 */
abstract class PurchaseItem extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'purchase_item';
    }

    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['pricebuy', 'qautity', 'products_id', 'purchase_id'], 'required'],
            [['qautity', 'products_id', 'purchase_id'], 'integer'],
            [['date_exp'], 'safe'],
            [['date'], 'string', 'max' => 45],
            [['pricebuy'], 'string', 'max' => 255],
            [['purchase_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Purchase::className(), 'targetAttribute' => ['purchase_id' => 'id']],
            [['products_id'], 'exist', 'skipOnError' => true, 'targetClass' => \app\models\Products::className(), 'targetAttribute' => ['products_id' => 'id']]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => Yii::t('models', 'ID'),
            'date' => Yii::t('models', 'Date'),
            'pricebuy' => Yii::t('models', 'Pricebuy'),
            'qautity' => Yii::t('models', 'Qautity'),
            'date_exp' => Yii::t('models', 'Date Exp'),
            'products_id' => Yii::t('models', 'Products ID'),
            'purchase_id' => Yii::t('models', 'Purchase ID'),
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPurchase()
    {
        return $this->hasOne(\app\models\Purchase::className(), ['id' => 'purchase_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getProducts()
    {
        return $this->hasOne(\app\models\Products::className(), ['id' => 'products_id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSaleHasPurchases()
    {
        return $this->hasMany(\app\models\SaleHasPurchase::className(), ['purchase_item_id' => 'id']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getSales()
    {
        return $this->hasMany(\app\models\Sale::className(), ['id' => 'sale_id'])->viaTable('sale_has_purchase', ['purchase_item_id' => 'id']);
    }




}
