<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "shop_profile".
 *
 * @property integer $id
 * @property string $logo
 * @property string $shop_name
 * @property string $telephone
 * @property string $phone_number
 * @property string $email
 * @property string $adress
 * @property string $key_active
 * @property string $aliasModel
 */
abstract class ShopProfile extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'shop_profile';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['shop_name', 'adress'], 'required'],
            [['adress'], 'string'],
            [['logo', 'telephone', 'phone_number', 'email'], 'string', 'max' => 45],
            [['shop_name', 'key_active'], 'string', 'max' => 255]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'logo' => 'Logo',
            'shop_name' => 'Shop Name',
            'telephone' => 'Telephone',
            'phone_number' => 'Phone Number',
            'email' => 'Email',
            'adress' => 'Adress',
            'key_active' => 'Key Active',
        ];
    }




}
