<?php
// This class was automatically generated by a giiant build task
// You should not change it manually as it will be overwritten on next build

namespace app\models\base;

use Yii;

/**
 * This is the base-model class for table "still_pay".
 *
 * @property integer $id
 * @property string $name
 * @property string $details
 * @property string $price
 * @property string $date
 * @property integer $status
 * @property string $aliasModel
 */
abstract class StillPay extends \yii\db\ActiveRecord
{



    /**
     * @inheritdoc
     */
    public static function tableName()
    {
        return 'still_pay';
    }


    /**
     * @inheritdoc
     */
    public function rules()
    {
        return [
            [['name', 'details', 'price', 'date'], 'required'],
            [['details'], 'string'],
            [['date'], 'safe'],
            [['name', 'price'], 'string', 'max' => 255],
            [['status'], 'string', 'max' => 1]
        ];
    }

    /**
     * @inheritdoc
     */
    public function attributeLabels()
    {
        return [
            'id' => 'ID',
            'name' => 'ຊື່​ຜູ້​ຄ້າງ',
            'details' => '​ລາຍ​ລະ​ອຽດ',
            'price' => '​ຈ​ຳ​ນວນ​ເງີນ',
            'date' => '​ວັນ​ທີ',
            'status' => 'Status',
        ];
    }




}
